-- Task5
--移除使用教練名稱查詢課程的 function：
DROP FUNCTION IF EXISTS GET_COURSES_BY_COACH_NAME_AND_START_AT(VARCHAR, VARCHAR, TIMESTAMP);
--移除使用使用者 EMAIL 查詢所有預約紀錄的 function：
DROP FUNCTION IF EXISTS GET_COURSES_BOOKING_BY_USER_EMAIL(VARCHAR);
--移除以 EMAIL 查詢課程購買數量的 function：
DROP FUNCTION IF EXISTS GET_PURCHASED_CREDITS_BY_USER_EMAIL(VARCHAR);
--移除以 EMAIL 查詢課程已使用數量的 function：
DROP FUNCTION IF EXISTS GET_USED_CREDITS_BY_USER_EMAIL(VARCHAR);
--移除以 EMAIL 查詢課程剩餘數量的 function：
DROP FUNCTION IF EXISTS GET_REMAINING_CREDITS_BY_USER_EMAIL(VARCHAR);
-- Task6
-- 移除取得教練資料的 function：
DROP FUNCTION IF EXISTS GET_COACH_ORDER_BY_EXPERIENCE_YEARS();
-- 移除取得銷售紀錄資料的 function：
DROP FUNCTION IF EXISTS REPORT_CREDIT_PACKAGE_PURCHASE_BY_TIMESTAMP(TIMESTAMP, TIMESTAMP);
-- 移除以使用者預約課程狀態的 function：
DROP FUNCTION IF EXISTS REPORT_USER_COURSE_BOOKING_STATUS_BY_TIMESTAMP(TIMESTAMP, TIMESTAMP);