--Task1

DROP PROCEDURE IF EXISTS ADD_USER_WITH_EMAIL_CHECK;

DROP PROCEDURE IF EXISTS UPDATE_USER_BY_EMAIL;

DROP PROCEDURE IF EXISTS DELETE_USER_BY_EMAIL;

--Task2

DROP PROCEDURE IF EXISTS ADD_CREDIT_PACKAGE;

DROP PROCEDURE IF EXISTS ADD_CREDIT_PURCHASE_PACKAGE_BY_USER_NAME;

--Task3

DROP PROCEDURE IF EXISTS UPDATE_COACH_BY_USER_EMAIL;

DROP PROCEDURE IF EXISTS UPDATE_COACH_SKILLS_BY_USER_EMAIL;

DROP PROCEDURE IF EXISTS ADD_SKILL_BY_NAME;

DROP PROCEDURE IF EXISTS DELETE_SKILL_BY_NAME;

--Task4

DROP PROCEDURE IF EXISTS ADD_COURSE_BY_COACH_EMAIL;

--Task5

DROP PROCEDURE IF EXISTS ADD_COURSE_BOOKING_BY_USER_EMAIL;

DROP PROCEDURE IF EXISTS CANCEL_COURSE_BOOKING_BY_USER_EMAIL;

DROP PROCEDURE IF EXISTS JOIN_COURSE_BOOKING_BY_USER_EMAIL;